version: "3.9"
services:
  frontend:
    build: ./frontend/
    ports: 
      - "3000:3000"
  backend:
    build: ./backend/
    ports: 
      - "3001:3001"
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: